name: Playwright Tests
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - "apps/pwabuilder/**"
    branches: [ tests-final, staging, main ]
  pull_request:
    paths:
      - "apps/pwabuilder/**"
    branches: [ tests-final, staging, main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Test Globally
      run: npm install -g @playwright/test
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Playwright Test Locally
      run: npm install @playwright/test --save-dev
    - name: Run Playwright tests
      run: npx playwright test tests/basic.spec.ts tests/packaging.spec.ts tests/report-card.spec.ts
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
